# demo #####
Vagrant.configure("2") do |config|
  config.vm.define "chefmain" do |chefmain|
    chefmain.vm.box = "generic/centos7"
    chefmain.vm.network "private_network", ip: "192.168.50.100"
    chefmain.vm.hostname = "chefmain-001"
    chefmain.ssh.pty = true
    chefmain.vm.network :forwarded_port, guest: 8080, host: 9000
    chefmain.vm.provision "file", source: "~/workspace/chefdemo/chefmain_provision", destination: "/home/vagrant/"
    chefmain.vm.provision "shell", inline: "/bin/sh /home/vagrant/chefmain_provision/chefmain_bootstrap.sh"
  end
end
